version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm i jsonlint -g
      - npm -v
  pre_build:
    commands:
      - npm --version
      - npm install npm -g
      - npm i
      - npm run build
  build:
    commands:
      - echo "Packaging Cloudformation Templates"
      - aws cloudformation package --template-file cloudformation.yml --s3-bucket codepipeline-us-east-1-deploy --output-template-file packaged-template.yml
  post_build:
    commands:
artifacts:
  files:
    - packaged-template.yml
