function:
  Type: AWS::Lambda::Function
  Properties:
    Code: build/myFunction
    Description:
      Fn::Sub: myFunction in the ${AWS::StackName} stack
    FunctionName:
      Fn::Sub: ${AWS::StackName}-myFunction
    Handler: index.handler
    MemorySize: 128
    Runtime: nodejs14.x
    Timeout: 300
    Role:
      Fn::GetAtt:
        - myFunctionRole
        - Arn
role:
  Type: AWS::IAM::Role
  Properties:
    AssumeRolePolicyDocument:
      Statement:
        - Effect: Allow
          Action: sts:AssumeRole
          Principal:
            Service:
              Fn::Sub: lambda.amazonaws.com
